name: portfolio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  intl: ^0.20.2
  mime: ^2.0.0
  path_provider: ^2.1.5
  reorderables: ^0.6.0
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - env
  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-Bold.ttf
          weight: 700

        - asset: fonts/Lora-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: fonts/Lora-Italic.ttf
          style: italic
          weight: 400

        - asset: fonts/Lora-Medium.ttf
          weight: 500

        - asset: fonts/Lora-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: fonts/Lora-Regular.ttf
          weight: 400

        - asset: fonts/Lora-SemiBold.ttf
          weight: 600

        - asset: fonts/Lora-SemiBoldItalic.ttf
          style: italic
          weight: 600
